##kykim.yaml

#name
name: kykim

# System
gpu_num: 4
seed: 43

# Model
architecture: kykim/electra-kor-base

# Trainer
lr: 0.00002071889728509824
n_epochs: 10
batch_size: 16
weight_decay: 0.5
scheduler: linear

#data
data_folder:
  train_data: ./data/train.csv
  val_data: ./data/val.csv
  test_data: ./data/test.csv

aug_data_folder:
  train_data: ./data/aug_train.csv


