##test.yaml

#name
name:
  xlm_robberta_large: xlm-roberta-large
  snunlp: snunlp/KR-ELECTRA-discriminator
  kykim: kykim/electra-kor-base

# System
gpu_num: 0
seed: 43

# Model
checkpoint:
  xlm_robberta_large: xlm-roberta-large/checkpoint-7960
  snunlp: snunlp/checkpoint-31824
  kykim: kykim/checkpoint-7960

# Trainer
batch_size: 4

#data
data_folder:
  train_data: ./data/train.csv
  val_data: ./data/val.csv
  test_data: ./data/test.csv
