##xlm_robert_large.yaml

#name
name: xlm_roberta_large

# System
gpu_num: 4
seed: 43

# Model
architecture: xlm-roberta-large

# Trainer
lr: 0.000009
n_epochs: 10
batch_size: 16
weight_decay: 0.0
scheduler: cosine

#data
data_folder:
  train_data: ./data/train.csv
  val_data: ./data/val.csv
  test_data: ./data/test.csv

aug_data_folder:
  train_data: ./data/aug_train.csv
  tal_data: ./data/aug_val.csv
  test_data: ./data/aug_test.csv
